// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type CabinetBody = {
    /**
     * At most one per prescribed drug, and only where the supply has fallen to the reorder threshold. Absent while it is above it or a sealed spare is standing by, absent without a running course, and absent for a drug two course positions name — the weekly rate is a position's while the supply is the whole shelf's, so a hint folded from two of them would divide the cabinet by half the prescription.
     */
    reorder: Array<VialReorderBody>;
    vials: Array<VialBody>;
};

export type CompoundBody = {
    default_unit: 'мг' | 'мкг';
    icon: string;
    id: string;
    name_ru: string;
    route: string;
};

export type Course = {
    /**
     * What is prescribed. A course with nothing in it is refused.
     */
    items: Array<Item> | null;
    /**
     * The prescriber's own note about the course.
     */
    notes?: string;
    /**
     * The day the course begins, and the day every cycle week is counted from.
     */
    start_date: string;
    /**
     * A patient has at most one active course at a time.
     */
    status: 'active' | 'completed' | 'cancelled';
    /**
     * How long the course runs.
     */
    weeks: number;
};

export type CourseOutputBody = {
    /**
     * One per item, in the order they were sent.
     */
    item_ids: Array<string>;
    /**
     * The course.
     */
    protocol_id: string;
};

export type CreatedPatient = {
    /**
     * The patient's id. The same value the invitation link signs the person in as.
     */
    user_id: string;
};

export type CreatedProvider = {
    /**
     * The doctor's id. The same value the invitation link signs them in as.
     */
    user_id: string;
};

export type DayBody = {
    all_done: boolean;
    any_pending: boolean;
    cycle_week?: number;
    date: string;
    has_injection: boolean;
};

export type DayOutputBody = {
    cycle_week?: number;
    date: string;
    occurrences: Array<OccurrenceBody>;
};

export type DoseBandBody = {
    dose: DoseBody;
    range: TrendRangeBody;
};

export type DoseBody = {
    unit: 'мг' | 'мкг';
    value: number;
};

export type Drug = {
    default_unit?: 'мг' | 'мкг';
    icon?: string;
    /**
     * A drug already in the directory.
     */
    id?: string;
    /**
     * The drug's name, if it is not in the directory yet. A name already there resolves to that row whatever its case.
     */
    name_ru?: string;
    route?: string;
};

export type HeldBackInputBody = {
    /**
     * True puts the vial aside, false takes it back. Sending the value it already carries is not an error and does not move the day it was set aside on.
     */
    held_back: boolean;
};

export type Item = {
    cadence: 'weekly' | 'daily' | 'n_per_week';
    /**
     * What is prescribed. Required for an injection, optional for a supplement — the strip draws its glyph and its name from here — and refused for a weigh-in, which is not a prescription of a drug.
     */
    compound?: Drug;
    /**
     * ISO weekdays, 1 for Monday. Empty for a daily item and at least one for any other, because the two are read together and a mismatch makes the schedule disagree with itself.
     */
    days_of_week: Array<number> | null;
    /**
     * The item being kept, from an earlier reply. Absent for an item just added.
     */
    id?: string;
    kind: 'injection' | 'supplement' | 'weigh_in';
    /**
     * Whether the patient records taking it. False for a supplement the clinic tracks without asking.
     */
    loggable: boolean;
    /**
     * The titration bands. Required for an injection; absent for a supplement or a weigh-in, which carry no dose. They may leave gaps — a washout is deliberate — and may not overlap.
     */
    phases: Array<Phase> | null;
    /**
     * The slots within the day, as HH:MM. Two of them is two occurrences, logged apart.
     */
    times: Array<string> | null;
};

export type LabelPhotoOutputBody = {
    expires_at: string;
    url: string;
};

export type LabelUploadInputBody = {
    /**
     * What the client is about to upload. It decides the key's extension, and the read side serves the object as this and nothing else.
     */
    content_type: 'image/jpeg' | 'image/png' | 'image/heic';
};

export type LabelUploadOutputBody = {
    expires_at: string;
    key: string;
    url: string;
};

export type LogDoseInputBody = {
    /**
     * The client's own key. A retry from the offline queue carries the key generated when the patient tapped save, and the repeat answers what the first answered.
     */
    client_request_id: string;
    dose_unit: 'мг' | 'мкг';
    /**
     * What the patient took, which is what is recorded: the wizard's dose is editable, and a patient who steps down from what the course prescribes has done so. The prescription stays in the course, so the two can be compared.
     */
    dose_value: number;
    mood?: number;
    note?: string;
    /**
     * The stored key of the photo, under the patient's own prefix.
     */
    photo_path?: string;
    /**
     * The prescribed item this dose answers.
     */
    protocol_item_id: string;
    /**
     * The seven §03 names. The same set the diary's tags come from, because one action writes both rows.
     */
    side_effects?: Array<'nausea' | 'fatigue' | 'headache' | 'bloating' | 'insomnia' | 'site' | 'appetite'> | null;
    /**
     * The body zone, one of the ten the map draws.
     */
    site_code?: 'l-abdomen' | 'r-abdomen' | 'l-delt' | 'r-delt' | 'l-glute' | 'r-glute' | 'l-thigh' | 'r-thigh' | 'l-lback' | 'r-lback';
    /**
     * The vial it was drawn from. Absent when the picker was skipped, which costs that vial's count one dose — a truth about what is known.
     */
    vial_id?: string;
};

export type LogDoseOutputBody = {
    /**
     * Present when the outcome is written.
     */
    dose_event_id?: string;
    dose_unit?: string;
    /**
     * Read back off the event: what was recorded as taken.
     */
    dose_value?: number;
    /**
     * The day whose diary entry this dose wrote. The entry has no id of its own — the day is its identity.
     */
    journal_date?: string;
    outcome: 'written' | 'incomplete' | 'not_scheduled_today' | 'already_logged';
    vial_id?: string;
};

export type MacrosBody = {
    carbs: number;
    fat: number;
    kcal: number;
    protein: number;
};

export type Me = {
    /**
     * When the presented token stops being accepted.
     */
    expires_at: string;
    /**
     * The caller's name as the clinic wrote it. Absent for an account the clinic holds no profile for.
     */
    full_name?: string;
    /**
     * The product role the token asserts, from the cadence_role claim: patient, doctor or admin. Empty when the account has no profile yet, in which case no data endpoint will answer for it.
     */
    role: string;
    /**
     * The caller's user id. Every access policy is keyed on it.
     */
    sub: string;
};

export type MetricMetaBody = {
    /**
     * Which way the metric has to move for the patient to be getting better, and the side of the threshold that is well.
     */
    direction: 'up' | 'down';
    /**
     * Null for the five metrics the clinic sets no bound on — absent, and not a zero every reading would clear.
     */
    threshold: ThresholdBody | null;
    /**
     * The unit every point of this metric is in; a point carries none of its own.
     */
    unit: string;
};

export type MetricTrendBody = {
    meta: MetricMetaBody;
    metric: 'weight' | 'hrv' | 'rhr' | 'sleep' | 'bodyfat' | 'waist' | 'hip' | 'chest';
    /**
     * Oldest first, ties broken by identifier, and empty for a metric this patient has not measured in this window.
     */
    points: Array<TrendPointBody>;
};

export type NewPatientBody = {
    date_of_birth?: string;
    /**
     * Where the invitation is sent. Stored folded to lower case, which is the spelling the identity provider holds.
     */
    email: string;
    /**
     * The patient's name as the clinic writes it.
     */
    full_name: string;
    /**
     * Height in centimetres.
     */
    height_cm?: number;
    sex?: 'male' | 'female';
    /**
     * The care team. A doctor creating a patient has to be on it; an admin names whoever the clinic decided.
     */
    specialists: Array<SpecialistBody> | null;
    /**
     * Target weight in kilograms.
     */
    target_weight_kg?: number;
};

export type NewProviderBody = {
    /**
     * Where the invitation is sent. Stored folded to lower case, which is the spelling the identity provider holds.
     */
    email: string;
    /**
     * The doctor's name as the clinic writes it.
     */
    full_name: string;
    /**
     * What the clinic calls them, in Russian. Shown to a patient beside the name on their care team.
     */
    title_ru?: string;
};

export type NewVialBody = {
    compound_id: string;
    /**
     * What the box says, transcribed. Nothing computes with it.
     */
    concentration_label: string;
    expires_on: string;
    /**
     * A key this API minted at POST /v1/me/vials/label-photo-uploads. Refused where it points anywhere but the caller's own prefix — the object store has no row-level security, so the key is the only thing saying whose object it is.
     */
    label_photo_path?: string;
    location_ru?: string;
    lot?: string;
    total_amount: VialAmountBody;
};

export type OccurrenceBody = {
    date: string;
    dose?: DoseBody;
    kind: 'injection' | 'supplement' | 'weigh_in';
    protocol_item_id: string;
    status: 'done' | 'pending' | 'missed' | 'scheduled';
    time: string;
};

export type Phase = {
    dose_unit: 'мг' | 'мкг';
    dose_value: number;
    from_week: number;
    to_week: number;
};

export type PhotoOutputBody = {
    expires_at: string;
    url: string;
};

export type PhotoUploadInputBody = {
    /**
     * What the client is about to upload. It decides the key's extension, and the read side serves the object as this and nothing else.
     */
    content_type: 'image/jpeg' | 'image/png' | 'image/heic';
};

export type PhotoUploadOutputBody = {
    expires_at: string;
    /**
     * What to send as photo_path when recording the dose. The server minted it; a client-chosen key is never accepted.
     */
    key: string;
    /**
     * A signed PUT. It constrains the key and not the bytes: neither the content type nor the size is bound by the signature.
     */
    url: string;
};

export type Problem = {
    /**
     * An explanation specific to this occurrence.
     */
    detail?: string;
    /**
     * Per-field detail, present on validation failures.
     */
    errors?: Array<ProblemDetail> | null;
    /**
     * The request path this problem occurred on.
     */
    instance?: string;
    /**
     * Correlates this response with the server log.
     */
    request_id?: string;
    /**
     * The HTTP status code.
     */
    status: number;
    /**
     * A short summary of the problem type, stable across occurrences.
     */
    title: string;
    /**
     * A URI reference identifying the problem type.
     */
    type: string;
};

export type ProblemDetail = {
    /**
     * Where the problem is, e.g. body.dose.value.
     */
    location?: string;
    /**
     * What is wrong with the value at this location.
     */
    message: string;
};

export type ProtocolMarkBody = {
    date: string;
    /**
     * Null on a start mark: there is no dose to have come up from.
     */
    from: DoseBody | null;
    kind: 'start' | 'titration';
    to: DoseBody;
};

export type RecordInputBody = {
    /**
     * When the reading was taken, which is where it lands on the axis — not when it was entered. A reading measured after the server's own instant is refused.
     */
    measured_at: string;
    /**
     * The sleep score is absent: it is computed from imported sessions and there is nothing to type.
     */
    metric: 'weight' | 'hrv' | 'rhr' | 'bodyfat' | 'waist' | 'hip' | 'chest';
    note?: string;
    /**
     * In the unit the metric is read in, which the reply carries back.
     */
    value: number;
};

export type RecordedBody = {
    id: string;
    measured_at: string;
    metric: 'weight' | 'hrv' | 'rhr' | 'bodyfat' | 'waist' | 'hip' | 'chest';
    /**
     * Read back off the row rather than asserted. This operation writes nothing but a hand-typed reading, so it is the column's default on a column the patient holds no grant on.
     */
    source: 'manual' | 'healthkit' | 'health_connect';
    /**
     * The server's, off the metric: a point on the axis carries none of its own.
     */
    unit: string;
    value: number;
};

export type ReorderBody = {
    compound_id: string;
    weeks_left: number;
};

export type RosterPage = {
    /**
     * Pass as cursor for the following page. Absent on the last one.
     */
    next_cursor?: string;
    /**
     * The patients this caller may see, ordered by name.
     */
    patients: Array<RosterRow>;
};

export type RosterRow = {
    /**
     * Years, worked out by the server. Absent when the clinic has not entered a date of birth.
     */
    age: number | null;
    /**
     * The patient's name as the clinic wrote it.
     */
    full_name: string;
    /**
     * Where the patient is between the invitation and an account they use. Unknown when the identity provider could not be asked.
     */
    invite_state: 'accepted' | 'pending' | 'expired' | 'unknown';
    /**
     * The patient's id, and the key every later request about them is made on.
     */
    user_id: string;
};

export type RowBody = {
    cadence: 'weekly' | 'daily' | 'n_per_week';
    /**
     * Null when the item names no drug.
     */
    compound: CompoundBody | null;
    dose?: DoseBody;
    kind: 'injection' | 'supplement' | 'weigh_in';
    loggable: boolean;
    protocol_item_id: string;
    times: Array<string>;
    today_status?: 'done' | 'pending' | 'missed' | 'scheduled';
};

export type ScheduleOutputBody = {
    days: Array<DayBody>;
};

export type SessionBody = {
    /**
     * The device's IANA timezone as pg_timezone_names spells it: Europe/Moscow, Asia/Tbilisi.
     */
    timezone: string;
};

export type SpecialistBody = {
    care_role: 'endo' | 'dietitian' | 'nurse';
    /**
     * The one specialist who leads. At most one per patient.
     */
    primary?: boolean;
    provider_id: string;
};

export type StaffMember = {
    /**
     * The name as the clinic wrote it.
     */
    full_name: string;
    /**
     * doctor or admin.
     */
    role: string;
    /**
     * What a patient sees beside the name. Absent when the clinic stated none.
     */
    title_ru: string | null;
    /**
     * The identifier a care-team assignment names.
     */
    user_id: string;
};

export type StaffPage = {
    /**
     * Everyone who may be put on a care team, ordered by name.
     */
    staff: Array<StaffMember>;
};

export type StepBody = {
    from: DoseBody;
    on: string;
    to: DoseBody;
    week: number;
};

export type ThresholdBody = {
    value: number;
};

export type TodayBody = {
    /**
     * Absent outside the course and for a cancelled one.
     */
    cycle_week?: number;
    date: string;
    dose_logged_today: boolean;
    /**
     * Null until the nutrition context is built.
     */
    meal_count: number | null;
    /**
     * Null until the nutrition context is built.
     */
    meal_macros: MacrosBody | null;
    next_dose?: OccurrenceBody;
    next_dose_compound?: CompoundBody;
    next_titration?: StepBody;
    part_of_day: 'night' | 'morning' | 'afternoon' | 'evening';
    /**
     * Absent everywhere vial_doses_left is, and additionally when the supply is above the threshold or a sealed spare is standing by. The weekly rate is one course position's, which is why two positions naming one drug answer nothing rather than half a rate.
     */
    reorder?: ReorderBody;
    /**
     * Computed from what was logged, not frozen.
     */
    suggested_site: 'l-abdomen' | 'r-abdomen' | 'l-delt' | 'r-delt' | 'l-glute' | 'r-glute' | 'l-thigh' | 'r-thigh' | 'l-lback' | 'r-lback';
    /**
     * Null until the measurements context is built.
     */
    target_weight_kg: number | null;
    /**
     * Null until the nutrition context is built.
     */
    targets: MacrosBody | null;
    /**
     * Of the vial being drawn from, and only while a dose is still due today: absent once the day's injection is logged, on a day prescribing none, and outside a running course. Absent too when the patient holds no open, undisposed, not-held-back vial of that drug, when no phase covers the day, and when two course positions name the drug — the dose to divide by is ambiguous then, and the cabinet answers substance and status instead.
     */
    vial_doses_left?: number;
    week_protocol: Array<RowBody>;
    /**
     * Null until the measurements context is built.
     */
    weight_kg: number | null;
    /**
     * Null until the measurements context is built.
     */
    weight_series: Array<number> | null;
};

export type TrendBody = {
    /**
     * The prescribed dose over the window. Empty when the course draws no strip.
     */
    bands: Array<DoseBandBody>;
    /**
     * The day the strip opened and each day it changed, clipped to the same window.
     */
    marks: Array<ProtocolMarkBody>;
    metric: MetricTrendBody;
    /**
     * Null when the window covers no days at all, which only the cycle window does: the patient has no course, or the one they have has not started.
     */
    range: TrendRangeBody | null;
    /**
     * The IANA zone the range's days are the patient's own in.
     */
    timezone: string;
    window: '7d' | '4w' | '3m' | 'cycle';
};

export type TrendPointBody = {
    id: string;
    measured_at: string;
    value: number;
};

export type TrendRangeBody = {
    from: string;
    /**
     * Inclusive: a window is a set of days, not a subtraction.
     */
    through: string;
};

export type TrendsBody = {
    /**
     * All eight, in enumeration order, unmeasured ones included.
     */
    metrics: Array<MetricTrendBody>;
    /**
     * Null when the window covers no days at all, which only the cycle window does: the patient has no course, or the one they have has not started.
     */
    range: TrendRangeBody | null;
    /**
     * The IANA zone the range's days are the patient's own in.
     */
    timezone: string;
    window: '7d' | '4w' | '3m' | 'cycle';
};

export type VialAmountBody = {
    unit: 'мг' | 'мкг';
    value: number;
};

export type VialBody = {
    compound_id: string;
    /**
     * What the box says, transcribed. Nothing computes with it.
     */
    concentration_label: string;
    /**
     * The dose in force for this drug today. Absent for the same three reasons as doses_left.
     */
    current_dose?: VialDoseBody;
    disposed_at?: string;
    /**
     * Absent where no running course prescribes this drug, where two course positions name it, and on a vial that was thrown away: a count needs a dose to divide by, and a vial in the bin buys nothing.
     */
    doses_left?: number;
    expires_on: string;
    has_label_photo: boolean;
    /**
     * The day the patient set it aside. A held-back vial is chosen by nothing the server decides for them.
     */
    held_back_at?: string;
    id: string;
    location_ru?: string;
    lot?: string;
    /**
     * Absent while the vial is sealed; that absence is the whole of «sealed».
     */
    opened_at?: string;
    remaining_amount: VialAmountBody;
    status: 'disposed' | 'expiring' | 'sealed' | 'low' | 'active';
    total_amount: VialAmountBody;
};

export type VialDoseBody = {
    unit: 'мг' | 'мкг';
    value: number;
};

export type VialReorderBody = {
    compound_id: string;
    weeks_left: number;
};

export type DashboardOverviewData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Where to continue from, as the previous page's next_cursor. Absent asks for the first page.
         */
        cursor?: string;
        /**
         * How many patients the page carries.
         */
        limit?: number;
    };
    url: '/v1/dashboard/overview';
};

export type DashboardOverviewErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Forbidden
     */
    403: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
    /**
     * Service Unavailable
     */
    503: Problem;
};

export type DashboardOverviewError = DashboardOverviewErrors[keyof DashboardOverviewErrors];

export type DashboardOverviewResponses = {
    /**
     * OK
     */
    200: RosterPage;
};

export type DashboardOverviewResponse = DashboardOverviewResponses[keyof DashboardOverviewResponses];

export type GetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/me';
};

export type GetMeErrors = {
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
    /**
     * Service Unavailable
     */
    503: Problem;
};

export type GetMeError = GetMeErrors[keyof GetMeErrors];

export type GetMeResponses = {
    /**
     * OK
     */
    200: Me;
};

export type GetMeResponse = GetMeResponses[keyof GetMeResponses];

export type LogDoseData = {
    body: LogDoseInputBody;
    path?: never;
    query?: never;
    url: '/v1/me/dose-events';
};

export type LogDoseErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Forbidden
     */
    403: Problem;
    /**
     * Conflict
     */
    409: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
    /**
     * Service Unavailable
     */
    503: Problem;
};

export type LogDoseError = LogDoseErrors[keyof LogDoseErrors];

export type LogDoseResponses = {
    /**
     * OK
     */
    200: LogDoseOutputBody;
};

export type LogDoseResponse = LogDoseResponses[keyof LogDoseResponses];

export type StartDosePhotoUploadData = {
    body: PhotoUploadInputBody;
    path?: never;
    query?: never;
    url: '/v1/me/dose-events/photo-uploads';
};

export type StartDosePhotoUploadErrors = {
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Forbidden
     */
    403: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type StartDosePhotoUploadError = StartDosePhotoUploadErrors[keyof StartDosePhotoUploadErrors];

export type StartDosePhotoUploadResponses = {
    /**
     * Created
     */
    201: PhotoUploadOutputBody;
};

export type StartDosePhotoUploadResponse = StartDosePhotoUploadResponses[keyof StartDosePhotoUploadResponses];

export type ReadDosePhotoData = {
    body?: never;
    path: {
        eventId: string;
    };
    query?: never;
    url: '/v1/me/dose-events/{eventId}/photo';
};

export type ReadDosePhotoErrors = {
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Forbidden
     */
    403: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
    /**
     * Service Unavailable
     */
    503: Problem;
};

export type ReadDosePhotoError = ReadDosePhotoErrors[keyof ReadDosePhotoErrors];

export type ReadDosePhotoResponses = {
    /**
     * OK
     */
    200: PhotoOutputBody;
};

export type ReadDosePhotoResponse = ReadDosePhotoResponses[keyof ReadDosePhotoResponses];

export type RecordMeasurementData = {
    body: RecordInputBody;
    path?: never;
    query?: never;
    url: '/v1/me/measurements';
};

export type RecordMeasurementErrors = {
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Forbidden
     */
    403: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
    /**
     * Service Unavailable
     */
    503: Problem;
};

export type RecordMeasurementError = RecordMeasurementErrors[keyof RecordMeasurementErrors];

export type RecordMeasurementResponses = {
    /**
     * Created
     */
    201: RecordedBody;
};

export type RecordMeasurementResponse = RecordMeasurementResponses[keyof RecordMeasurementResponses];

export type DeleteMeasurementData = {
    body?: never;
    path: {
        /**
         * The reading, as the point on the axis carries it.
         */
        id: string;
    };
    query?: never;
    url: '/v1/me/measurements/{id}';
};

export type DeleteMeasurementErrors = {
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Forbidden
     */
    403: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Conflict
     */
    409: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
    /**
     * Service Unavailable
     */
    503: Problem;
};

export type DeleteMeasurementError = DeleteMeasurementErrors[keyof DeleteMeasurementErrors];

export type DeleteMeasurementResponses = {
    /**
     * No Content
     */
    204: void;
};

export type DeleteMeasurementResponse = DeleteMeasurementResponses[keyof DeleteMeasurementResponses];

export type GetScheduleMonthData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * The month to draw, as YYYY-MM. Defaults to the one the patient is in.
         */
        month?: string;
    };
    url: '/v1/me/schedule';
};

export type GetScheduleMonthErrors = {
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Forbidden
     */
    403: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
    /**
     * Service Unavailable
     */
    503: Problem;
};

export type GetScheduleMonthError = GetScheduleMonthErrors[keyof GetScheduleMonthErrors];

export type GetScheduleMonthResponses = {
    /**
     * OK
     */
    200: ScheduleOutputBody;
};

export type GetScheduleMonthResponse = GetScheduleMonthResponses[keyof GetScheduleMonthResponses];

export type GetScheduleDayData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * The day to open. Defaults to the patient's today.
         */
        date?: string;
    };
    url: '/v1/me/schedule/day';
};

export type GetScheduleDayErrors = {
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Forbidden
     */
    403: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
    /**
     * Service Unavailable
     */
    503: Problem;
};

export type GetScheduleDayError = GetScheduleDayErrors[keyof GetScheduleDayErrors];

export type GetScheduleDayResponses = {
    /**
     * OK
     */
    200: DayOutputBody;
};

export type GetScheduleDayResponse = GetScheduleDayResponses[keyof GetScheduleDayResponses];

export type RecordSessionData = {
    body: SessionBody;
    path?: never;
    query?: never;
    url: '/v1/me/session';
};

export type RecordSessionErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Forbidden
     */
    403: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
    /**
     * Service Unavailable
     */
    503: Problem;
};

export type RecordSessionError = RecordSessionErrors[keyof RecordSessionErrors];

export type RecordSessionResponses = {
    /**
     * No Content
     */
    204: void;
};

export type RecordSessionResponse = RecordSessionResponses[keyof RecordSessionResponses];

export type GetTodayData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/me/today';
};

export type GetTodayErrors = {
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Forbidden
     */
    403: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
    /**
     * Service Unavailable
     */
    503: Problem;
};

export type GetTodayError = GetTodayErrors[keyof GetTodayErrors];

export type GetTodayResponses = {
    /**
     * OK
     */
    200: TodayBody;
};

export type GetTodayResponse = GetTodayResponses[keyof GetTodayResponses];

export type GetTrendsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * The span to draw. The cycle window is the last course's geometry, so its width depends on the course rather than on the calendar.
         */
        window?: '7d' | '4w' | '3m' | 'cycle';
    };
    url: '/v1/me/trends';
};

export type GetTrendsErrors = {
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Forbidden
     */
    403: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
    /**
     * Service Unavailable
     */
    503: Problem;
};

export type GetTrendsError = GetTrendsErrors[keyof GetTrendsErrors];

export type GetTrendsResponses = {
    /**
     * OK
     */
    200: TrendsBody;
};

export type GetTrendsResponse = GetTrendsResponses[keyof GetTrendsResponses];

export type GetMetricTrendData = {
    body?: never;
    path: {
        metric: 'weight' | 'hrv' | 'rhr' | 'sleep' | 'bodyfat' | 'waist' | 'hip' | 'chest';
    };
    query?: {
        /**
         * The span to draw. The cycle window is the last course's geometry, so its width depends on the course rather than on the calendar.
         */
        window?: '7d' | '4w' | '3m' | 'cycle';
    };
    url: '/v1/me/trends/{metric}';
};

export type GetMetricTrendErrors = {
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Forbidden
     */
    403: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
    /**
     * Service Unavailable
     */
    503: Problem;
};

export type GetMetricTrendError = GetMetricTrendErrors[keyof GetMetricTrendErrors];

export type GetMetricTrendResponses = {
    /**
     * OK
     */
    200: TrendBody;
};

export type GetMetricTrendResponse = GetMetricTrendResponses[keyof GetMetricTrendResponses];

export type ReadCabinetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/me/vials';
};

export type ReadCabinetErrors = {
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Forbidden
     */
    403: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
    /**
     * Service Unavailable
     */
    503: Problem;
};

export type ReadCabinetError = ReadCabinetErrors[keyof ReadCabinetErrors];

export type ReadCabinetResponses = {
    /**
     * OK
     */
    200: CabinetBody;
};

export type ReadCabinetResponse = ReadCabinetResponses[keyof ReadCabinetResponses];

export type AddVialData = {
    body: NewVialBody;
    path?: never;
    query?: never;
    url: '/v1/me/vials';
};

export type AddVialErrors = {
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Forbidden
     */
    403: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
    /**
     * Service Unavailable
     */
    503: Problem;
};

export type AddVialError = AddVialErrors[keyof AddVialErrors];

export type AddVialResponses = {
    /**
     * Created
     */
    201: VialBody;
};

export type AddVialResponse = AddVialResponses[keyof AddVialResponses];

export type StartLabelPhotoUploadData = {
    body: LabelUploadInputBody;
    path?: never;
    query?: never;
    url: '/v1/me/vials/label-photo-uploads';
};

export type StartLabelPhotoUploadErrors = {
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Forbidden
     */
    403: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
};

export type StartLabelPhotoUploadError = StartLabelPhotoUploadErrors[keyof StartLabelPhotoUploadErrors];

export type StartLabelPhotoUploadResponses = {
    /**
     * Created
     */
    201: LabelUploadOutputBody;
};

export type StartLabelPhotoUploadResponse = StartLabelPhotoUploadResponses[keyof StartLabelPhotoUploadResponses];

export type ReadVialData = {
    body?: never;
    path: {
        vialId: string;
    };
    query?: never;
    url: '/v1/me/vials/{vialId}';
};

export type ReadVialErrors = {
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Forbidden
     */
    403: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
    /**
     * Service Unavailable
     */
    503: Problem;
};

export type ReadVialError = ReadVialErrors[keyof ReadVialErrors];

export type ReadVialResponses = {
    /**
     * OK
     */
    200: VialBody;
};

export type ReadVialResponse = ReadVialResponses[keyof ReadVialResponses];

export type DisposeOfAVialData = {
    body?: never;
    path: {
        vialId: string;
    };
    query?: never;
    url: '/v1/me/vials/{vialId}/dispose';
};

export type DisposeOfAVialErrors = {
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Forbidden
     */
    403: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Conflict
     */
    409: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
    /**
     * Service Unavailable
     */
    503: Problem;
};

export type DisposeOfAVialError = DisposeOfAVialErrors[keyof DisposeOfAVialErrors];

export type DisposeOfAVialResponses = {
    /**
     * OK
     */
    200: VialBody;
};

export type DisposeOfAVialResponse = DisposeOfAVialResponses[keyof DisposeOfAVialResponses];

export type HoldAVialBackData = {
    body: HeldBackInputBody;
    path: {
        vialId: string;
    };
    query?: never;
    url: '/v1/me/vials/{vialId}/held-back';
};

export type HoldAVialBackErrors = {
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Forbidden
     */
    403: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Conflict
     */
    409: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
    /**
     * Service Unavailable
     */
    503: Problem;
};

export type HoldAVialBackError = HoldAVialBackErrors[keyof HoldAVialBackErrors];

export type HoldAVialBackResponses = {
    /**
     * OK
     */
    200: VialBody;
};

export type HoldAVialBackResponse = HoldAVialBackResponses[keyof HoldAVialBackResponses];

export type ReadVialLabelPhotoData = {
    body?: never;
    path: {
        vialId: string;
    };
    query?: never;
    url: '/v1/me/vials/{vialId}/label-photo';
};

export type ReadVialLabelPhotoErrors = {
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Forbidden
     */
    403: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
    /**
     * Service Unavailable
     */
    503: Problem;
};

export type ReadVialLabelPhotoError = ReadVialLabelPhotoErrors[keyof ReadVialLabelPhotoErrors];

export type ReadVialLabelPhotoResponses = {
    /**
     * OK
     */
    200: LabelPhotoOutputBody;
};

export type ReadVialLabelPhotoResponse = ReadVialLabelPhotoResponses[keyof ReadVialLabelPhotoResponses];

export type CreatePatientData = {
    body: NewPatientBody;
    path?: never;
    query?: never;
    url: '/v1/patients';
};

export type CreatePatientErrors = {
    /**
     * Error
     */
    default: Problem;
};

export type CreatePatientError = CreatePatientErrors[keyof CreatePatientErrors];

export type CreatePatientResponses = {
    /**
     * Created
     */
    201: CreatedPatient;
};

export type CreatePatientResponse = CreatePatientResponses[keyof CreatePatientResponses];

export type CreateProtocolData = {
    body: Course;
    path: {
        /**
         * The patient the course is for.
         */
        patientId: string;
    };
    query?: never;
    url: '/v1/patients/{patientId}/protocols';
};

export type CreateProtocolErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Forbidden
     */
    403: Problem;
    /**
     * Conflict
     */
    409: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
    /**
     * Service Unavailable
     */
    503: Problem;
};

export type CreateProtocolError = CreateProtocolErrors[keyof CreateProtocolErrors];

export type CreateProtocolResponses = {
    /**
     * Created
     */
    201: CourseOutputBody;
};

export type CreateProtocolResponse = CreateProtocolResponses[keyof CreateProtocolResponses];

export type ReplaceProtocolData = {
    body: Course;
    path: {
        /**
         * The patient the course is for.
         */
        patientId: string;
        /**
         * The course being rewritten.
         */
        protocolId: string;
    };
    query?: never;
    url: '/v1/patients/{patientId}/protocols/{protocolId}';
};

export type ReplaceProtocolErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Forbidden
     */
    403: Problem;
    /**
     * Not Found
     */
    404: Problem;
    /**
     * Conflict
     */
    409: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
    /**
     * Service Unavailable
     */
    503: Problem;
};

export type ReplaceProtocolError = ReplaceProtocolErrors[keyof ReplaceProtocolErrors];

export type ReplaceProtocolResponses = {
    /**
     * OK
     */
    200: CourseOutputBody;
};

export type ReplaceProtocolResponse = ReplaceProtocolResponses[keyof ReplaceProtocolResponses];

export type ListProvidersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/providers';
};

export type ListProvidersErrors = {
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Forbidden
     */
    403: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
    /**
     * Service Unavailable
     */
    503: Problem;
};

export type ListProvidersError = ListProvidersErrors[keyof ListProvidersErrors];

export type ListProvidersResponses = {
    /**
     * OK
     */
    200: StaffPage;
};

export type ListProvidersResponse = ListProvidersResponses[keyof ListProvidersResponses];

export type CreateProviderData = {
    body: NewProviderBody;
    path?: never;
    query?: never;
    url: '/v1/providers';
};

export type CreateProviderErrors = {
    /**
     * Error
     */
    default: Problem;
};

export type CreateProviderError = CreateProviderErrors[keyof CreateProviderErrors];

export type CreateProviderResponses = {
    /**
     * Created
     */
    201: CreatedProvider;
};

export type CreateProviderResponse = CreateProviderResponses[keyof CreateProviderResponses];
