// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type CreatedPatient = {
    /**
     * The patient's id. The same value the invitation link signs the person in as.
     */
    user_id: string;
};

export type CreatedProvider = {
    /**
     * The doctor's id. The same value the invitation link signs them in as.
     */
    user_id: string;
};

export type Me = {
    /**
     * When the presented token stops being accepted.
     */
    expires_at: string;
    /**
     * The caller's name as the clinic wrote it. Absent for an account the clinic holds no profile for.
     */
    full_name?: string;
    /**
     * The product role the token asserts, from the cadence_role claim: patient, doctor or admin. Empty when the account has no profile yet, in which case no data endpoint will answer for it.
     */
    role: string;
    /**
     * The caller's user id. Every access policy is keyed on it.
     */
    sub: string;
};

export type NewPatientBody = {
    date_of_birth?: string;
    /**
     * Where the invitation is sent. Stored folded to lower case, which is the spelling the identity provider holds.
     */
    email: string;
    /**
     * The patient's name as the clinic writes it.
     */
    full_name: string;
    /**
     * Height in centimetres.
     */
    height_cm?: number;
    sex?: 'male' | 'female';
    /**
     * The care team. A doctor creating a patient has to be on it; an admin names whoever the clinic decided.
     */
    specialists: Array<SpecialistBody> | null;
    /**
     * Target weight in kilograms.
     */
    target_weight_kg?: number;
};

export type NewProviderBody = {
    /**
     * Where the invitation is sent. Stored folded to lower case, which is the spelling the identity provider holds.
     */
    email: string;
    /**
     * The doctor's name as the clinic writes it.
     */
    full_name: string;
    /**
     * What the clinic calls them, in Russian. Shown to a patient beside the name on their care team.
     */
    title_ru?: string;
};

export type Problem = {
    /**
     * An explanation specific to this occurrence.
     */
    detail?: string;
    /**
     * Per-field detail, present on validation failures.
     */
    errors?: Array<ProblemDetail> | null;
    /**
     * The request path this problem occurred on.
     */
    instance?: string;
    /**
     * Correlates this response with the server log.
     */
    request_id?: string;
    /**
     * The HTTP status code.
     */
    status: number;
    /**
     * A short summary of the problem type, stable across occurrences.
     */
    title: string;
    /**
     * A URI reference identifying the problem type.
     */
    type: string;
};

export type ProblemDetail = {
    /**
     * Where the problem is, e.g. body.dose.value.
     */
    location?: string;
    /**
     * What is wrong with the value at this location.
     */
    message: string;
};

export type RosterPage = {
    /**
     * Pass as cursor for the following page. Absent on the last one.
     */
    next_cursor?: string;
    /**
     * The patients this caller may see, ordered by name.
     */
    patients: Array<RosterRow>;
};

export type RosterRow = {
    /**
     * Years, worked out by the server. Absent when the clinic has not entered a date of birth.
     */
    age: number | null;
    /**
     * The patient's name as the clinic wrote it.
     */
    full_name: string;
    /**
     * Where the patient is between the invitation and an account they use. Unknown when the identity provider could not be asked.
     */
    invite_state: 'accepted' | 'pending' | 'expired' | 'unknown';
    /**
     * The patient's id, and the key every later request about them is made on.
     */
    user_id: string;
};

export type SessionBody = {
    /**
     * The device's IANA timezone as pg_timezone_names spells it: Europe/Moscow, Asia/Tbilisi.
     */
    timezone: string;
};

export type SpecialistBody = {
    care_role: 'endo' | 'dietitian' | 'nurse';
    /**
     * The one specialist who leads. At most one per patient.
     */
    primary?: boolean;
    provider_id: string;
};

export type StaffMember = {
    /**
     * The name as the clinic wrote it.
     */
    full_name: string;
    /**
     * doctor or admin.
     */
    role: string;
    /**
     * What a patient sees beside the name. Absent when the clinic stated none.
     */
    title_ru: string | null;
    /**
     * The identifier a care-team assignment names.
     */
    user_id: string;
};

export type StaffPage = {
    /**
     * Everyone who may be put on a care team, ordered by name.
     */
    staff: Array<StaffMember>;
};

export type DashboardOverviewData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Where to continue from, as the previous page's next_cursor. Absent asks for the first page.
         */
        cursor?: string;
        /**
         * How many patients the page carries.
         */
        limit?: number;
    };
    url: '/v1/dashboard/overview';
};

export type DashboardOverviewErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Forbidden
     */
    403: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
    /**
     * Service Unavailable
     */
    503: Problem;
};

export type DashboardOverviewError = DashboardOverviewErrors[keyof DashboardOverviewErrors];

export type DashboardOverviewResponses = {
    /**
     * OK
     */
    200: RosterPage;
};

export type DashboardOverviewResponse = DashboardOverviewResponses[keyof DashboardOverviewResponses];

export type GetMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/me';
};

export type GetMeErrors = {
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
    /**
     * Service Unavailable
     */
    503: Problem;
};

export type GetMeError = GetMeErrors[keyof GetMeErrors];

export type GetMeResponses = {
    /**
     * OK
     */
    200: Me;
};

export type GetMeResponse = GetMeResponses[keyof GetMeResponses];

export type RecordSessionData = {
    body: SessionBody;
    path?: never;
    query?: never;
    url: '/v1/me/session';
};

export type RecordSessionErrors = {
    /**
     * Bad Request
     */
    400: Problem;
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Forbidden
     */
    403: Problem;
    /**
     * Unprocessable Entity
     */
    422: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
    /**
     * Service Unavailable
     */
    503: Problem;
};

export type RecordSessionError = RecordSessionErrors[keyof RecordSessionErrors];

export type RecordSessionResponses = {
    /**
     * No Content
     */
    204: void;
};

export type RecordSessionResponse = RecordSessionResponses[keyof RecordSessionResponses];

export type CreatePatientData = {
    body: NewPatientBody;
    path?: never;
    query?: never;
    url: '/v1/patients';
};

export type CreatePatientErrors = {
    /**
     * Error
     */
    default: Problem;
};

export type CreatePatientError = CreatePatientErrors[keyof CreatePatientErrors];

export type CreatePatientResponses = {
    /**
     * Created
     */
    201: CreatedPatient;
};

export type CreatePatientResponse = CreatePatientResponses[keyof CreatePatientResponses];

export type ListProvidersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/v1/providers';
};

export type ListProvidersErrors = {
    /**
     * Unauthorized
     */
    401: Problem;
    /**
     * Forbidden
     */
    403: Problem;
    /**
     * Internal Server Error
     */
    500: Problem;
    /**
     * Service Unavailable
     */
    503: Problem;
};

export type ListProvidersError = ListProvidersErrors[keyof ListProvidersErrors];

export type ListProvidersResponses = {
    /**
     * OK
     */
    200: StaffPage;
};

export type ListProvidersResponse = ListProvidersResponses[keyof ListProvidersResponses];

export type CreateProviderData = {
    body: NewProviderBody;
    path?: never;
    query?: never;
    url: '/v1/providers';
};

export type CreateProviderErrors = {
    /**
     * Error
     */
    default: Problem;
};

export type CreateProviderError = CreateProviderErrors[keyof CreateProviderErrors];

export type CreateProviderResponses = {
    /**
     * Created
     */
    201: CreatedProvider;
};

export type CreateProviderResponse = CreateProviderResponses[keyof CreateProviderResponses];
