// Writes src/icons/icons.ts: the icons the dashboard's prototype actually draws, with their paths.
//
//   node scripts/derive-icons.ts          rewrites the module
//   node scripts/derive-icons.ts --check  fails if the module has drifted from the prototype
//
// Derived and not retyped. A hand-written list was tried and came out both too long — icons belonging
// to components the dashboard does not render — and too short, missing the side menu and the activity
// feed. Two greps of the same author disagreed with each other, which is the whole argument for a
// script.
//
// The sweep is over every quoted string in the three files, intersected with what heroicons.js
// actually carries, rather than over the syntax that names an icon. Measured: reading `Icon name="…"`
// and `icon: '…'` misses `icon="check-circle"` in dd-app.jsx — an attribute rather than a field, one
// spelling among several, and exactly the kind a syntax list forgets. Intersecting with the source of
// truth is what makes the wide net safe: a string that is not an icon cannot become one.
import { readFileSync, writeFileSync } from 'node:fs'

const HEROICONS = 'prototype/design-system/heroicons.js'
const MODULE = 'src/icons/icons.ts'

// dd-chat* is left out because chat is another screen and out of this block's scope, and
// design-system/ is the mobile app's own components — AppHeader, IconBtn, TabBar, Spark — which this
// dashboard does not render.
const DRAWN_BY = ['prototype/dd-app.jsx', 'prototype/dd-components.jsx', 'prototype/dd-data.jsx']

const heroicons = readFileSync(HEROICONS, 'utf8')

// The `d` attributes rather than the markup, because that is all the markup carries: measured over
// all 44 paths of the source, every element is a <path> and every one of them is round-capped and
// round-joined. Structured data lets the component render elements instead of injecting HTML.
const available = new Map<string, string[]>()
for (const [, name, markup] of heroicons.matchAll(/^\s*'([a-z0-9-]+)'\s*:\s*'(.+)',\s*$/gm)) {
  if (!name || !markup) continue

  const outline = [...markup.matchAll(/\sd="([^"]+)"/g)].map(([, d]) => d ?? '')
  if (outline.length === 0) {
    throw new Error(`${name} carries no path, so it would render as nothing`)
  }

  available.set(name, outline)
}

if (available.size === 0) {
  throw new Error(`${HEROICONS} yielded no icons, so this derivation measured nothing`)
}

const quoted = new Set<string>()
for (const source of DRAWN_BY) {
  for (const [, text] of readFileSync(source, 'utf8').matchAll(/['"]([a-z0-9-]+)['"]/g)) {
    if (text) quoted.add(text)
  }
}

const drawn = [...available.keys()].filter((name) => quoted.has(name)).sort()

if (drawn.length === 0) {
  throw new Error('no icon of the prototype was found in the dashboard, which cannot be right')
}

const rendered = `// Generated by scripts/derive-icons.ts from the prototype. Do not edit by hand.
//
// The icons the dashboard draws and no others: the set is derived from what the prototype references,
// so a screen that stops using one drops it from the bundle, and a name nothing draws cannot sit here
// unnoticed. Each entry is the icon's path data; every one draws round-capped and round-joined into a
// 24x24 box, which is what heroicons.js says and what the component applies.

export const icons = {
${drawn.map((name) => `  '${name}': ${JSON.stringify(available.get(name))},`).join('\n')}
} as const satisfies Record<string, readonly string[]>

/** Every icon this application may name. An unknown one is a compile error. */
export type IconName = keyof typeof icons
`

if (process.argv.includes('--check')) {
  if (readFileSync(MODULE, 'utf8') !== rendered) {
    console.error(`${MODULE} is not what the prototype derives — run: npm run icons`)
    process.exit(1)
  }

  console.log(`${MODULE} matches the prototype: ${drawn.length} icons`)
} else {
  writeFileSync(MODULE, rendered)
  console.log(`wrote ${MODULE}: ${drawn.length} icons`)
}
