// A one-off, like derive-icons' seed half: reads the prototype's own data and writes
// src/data/fixtures/overview.ts with every derived number already worked out.
//
//   node scripts/seed-overview-fixture.ts
//
// Run once and the output is committed. It is not a standing generator and the gate does not re-run
// it: the fixture is scaffolding that the first live read replaces, and pinning it to a frozen
// prototype for the rest of its life would be pinning the wrong thing.
//
// The arithmetic is the prototype's own — its `lost` and `lostPct`, its STATS — evaluated rather than
// reimplemented. Rewriting it here would be a second implementation to disagree with the first, and
// the whole reason these numbers move out of the components is that there should be one.
// The rules below are off for this file and this file only. Evaluating the prototype is the whole
// method — reimplementing its arithmetic is the thing this avoids — and what is evaluated is a file
// frozen in this repository, read at author time by a script the gate never runs. Nothing here reaches
// a browser, a request or a build.
/* eslint-disable @typescript-eslint/no-explicit-any, @typescript-eslint/no-implied-eval,
   @typescript-eslint/no-unsafe-call, @typescript-eslint/no-unsafe-assignment,
   @typescript-eslint/no-unsafe-member-access, @typescript-eslint/no-unsafe-argument,
   @typescript-eslint/no-unsafe-return */
import { readFileSync, writeFileSync } from 'node:fs'

const prototype: Record<string, any> = {}
new Function('window', readFileSync('prototype/dd-data.jsx', 'utf8'))(prototype)

// The thresholds the prototype hard-codes in dd-app.jsx:214-216, which is what the acceptance
// criterion moves into the data. The verdict travels with them; a test keeps the two in step.
const BIOMARKERS = [
  { key: 'hrv', label: 'HRV', unit: 'мс', range: { min: 58 } },
  { key: 'rhr', label: 'ЧСС покоя', unit: 'уд/мин', range: { max: 60 } },
  { key: 'sleep', label: 'Сон', unit: '/100', range: { min: 75 } },
]

/** «0,25 мг» back into the quantity it was before somebody wrote it out. */
function splitDose(written: string): { value: number; unit: string } {
  const parsed = /^([\d,.]+)\s*(.+)$/.exec(written.trim())
  if (!parsed?.[1] || !parsed[2]) {
    throw new Error(`the prototype writes the dose as "${written}", which is not a quantity and a unit`)
  }

  return { value: Number(parsed[1].replace(',', '.')), unit: parsed[2] }
}

const within = (value: number, range: { min?: number; max?: number }) =>
  (range.min === undefined || value >= range.min) && (range.max === undefined || value <= range.max)

const patients = prototype.PATIENTS.map((p: any) => ({
  id: p.id,
  name: p.name,
  age: p.age,
  initial: p.initial,
  compound: p.compound,
  dose: splitDose(p.dose),
  cadence: p.cadence,
  week: p.week,
  cycleLength: p.cycleLen,
  status: p.status,
  adherence: p.adherence,
  lastSeen: p.lastSeen,
  flags: p.flags,
  note: p.note,
  weight: p.weight,
  weightStart: p.weightStart,
  goal: p.goal,
  unit: p.unit,
  lostKg: prototype.lost(p),
  goalProgressPct: prototype.lostPct(p),
  spark: p.spark,
  biomarkers: BIOMARKERS.map((marker) => ({
    ...marker,
    value: p.metrics[marker.key],
    withinRange: within(p.metrics[marker.key], marker.range),
  })),
}))

const count = (status: string) => patients.filter((p: any) => p.status === status).length

const overview = {
  doctor: { name: prototype.DOCTOR.name, initial: prototype.DOCTOR.initial },
  aggregates: {
    patients: prototype.STATS.total,
    attention: prototype.STATS.attention,
    watch: prototype.STATS.watch,
    dosesToday: prototype.STATS.dosesToday,
    dosesDone: prototype.STATS.dosesDone,
    unread: prototype.STATS.unread,
    averageAdherence: prototype.STATS.avgAdh,
    byStatus: {
      all: patients.length,
      attention: count('attention'),
      watch: count('watch'),
      track: count('track'),
    },
  },
  triage: patients.filter((p: any) => p.status === 'attention').map((p: any) => p.id),
  schedule: prototype.SCHEDULE.map((s: any) => ({
    id: s.id,
    patientId: s.patientId,
    patientName: prototype.patientById(s.patientId).name,
    at: s.time,
    kind: s.kind,
    label: s.label,
    state: s.state,
  })),
}

const module = `// Generated once by scripts/seed-overview-fixture.ts from the frozen prototype. Committed, and not
// regenerated by the gate: this is scaffolding the first live read replaces, and pinning it to the
// prototype for the rest of its life would pin the wrong thing.
//
// Every derived number is already here — what a patient has lost, how far along the goal they are, the
// stats strip, the roster tab counters, the biomarker verdicts. The prototype worked all of them out in
// its components; this is the same arithmetic, done once and on the far side of the seam.
import type { Overview, Patient } from '../overview'

export const PATIENTS: readonly Patient[] = ${JSON.stringify(patients, null, 2)}

export const TRIAGE_IDS: readonly string[] = ${JSON.stringify(overview.triage)}

export const OVERVIEW: Omit<Overview, 'triage'> = ${JSON.stringify(
  { doctor: overview.doctor, aggregates: overview.aggregates, schedule: overview.schedule },
  null,
  2,
)}
`

writeFileSync('src/data/fixtures/overview.ts', module)
console.log(`wrote src/data/fixtures/overview.ts: ${patients.length} patients, ${overview.schedule.length} schedule entries`)
