// Reads the design tokens out of the ported CSS and renders them as a typed module.
//
// The CSS is the source and TypeScript is the output, never the other way round: the port is verbatim
// (see src/tokens/port.test.ts), so anything generated from it stays true to the prototype by
// construction. What generation adds is that a typo in a token name becomes a compile error instead of
// an `undefined` that renders as a transparent colour.

export type Token = {
  /** The key the generated module exports it under. */
  name: string
  /** The custom property, for the half of the styling that stays in CSS. */
  cssVariable: string
  /** Resolved: an alias carries the value it ends at, not the reference. */
  value: string
}

/** parseTokens reads the first `:root` block and resolves every alias to a final value. */
export function parseTokens(css: string): Token[] {
  const declarations = readDeclarations(firstRoot(stripComments(css)))
  const byVariable = new Map(declarations.map(({ cssVariable, value }) => [cssVariable, value]))

  const tokens = declarations.map(({ cssVariable, value }) => ({
    name: camelCase(cssVariable),
    cssVariable,
    value: resolve(cssVariable, value, byVariable, new Set()),
  }))

  refuseCollisions(tokens)

  return tokens
}

/** renderModule writes the tokens out as the committed TypeScript source. */
export function renderModule(tokens: Token[]): string {
  const entries = (pick: (token: Token) => string) =>
    tokens.map((token) => `  ${token.name}: ${quote(pick(token))},`).join('\n')

  return `// Generated by scripts/generate-tokens.ts from src/tokens/colors_and_type.css.
// Committed on purpose, and the gate regenerates it to catch drift — a generated file nobody can read
// in a diff is a file that stops being read at all.
//
// Aliases are resolved: \`--primary: var(--forest-700)\` arrives here as the colour, because a consumer
// asking for a token wants a value and not a second lookup.

/** Every design token, by the name TypeScript knows it under. */
export const tokens = {
${entries((token) => token.value)}
} as const

/** The same tokens as custom properties, for the styling that stays in CSS. */
export const cssVariables = {
${entries((token) => token.cssVariable)}
} as const

export type TokenName = keyof typeof tokens
`
}

// A scanner and not a regular expression, because the values are not a regular language: they carry
// nested parentheses (`cubic-bezier`, `rgba` inside a shadow) and quoted strings with commas in them.
function readDeclarations(root: string): Array<{ cssVariable: string; value: string }> {
  const declarations: Array<{ cssVariable: string; value: string }> = []

  let depth = 0
  let quoted: string | null = null
  let start = 0

  const take = (end: number) => {
    const text = root.slice(start, end).trim()
    start = end + 1

    if (!text.startsWith('--')) return

    const colon = text.indexOf(':')
    if (colon < 0) throw new Error(`the declaration "${text}" has no value`)

    declarations.push({
      cssVariable: text.slice(0, colon).trim(),
      value: text.slice(colon + 1).trim(),
    })
  }

  for (let i = 0; i < root.length; i += 1) {
    const character = root[i]

    if (quoted) {
      if (character === quoted) quoted = null
      continue
    }

    if (character === "'" || character === '"') quoted = character
    else if (character === '(') depth += 1
    else if (character === ')') depth -= 1
    else if (character === ';' && depth === 0) take(i)
  }

  // A last declaration without its semicolon is a typo CSS forgives and this must not.
  if (root.slice(start).trim().startsWith('--')) {
    throw new Error(`the declaration "${root.slice(start).trim()}" is missing its semicolon`)
  }

  return declarations
}

function resolve(
  of: string,
  value: string,
  byVariable: Map<string, string>,
  seen: Set<string>,
): string {
  const alias = /^var\(\s*(--[a-z0-9-]+)\s*\)$/.exec(value)
  if (!alias?.[1]) return value

  const target = alias[1]
  if (seen.has(target)) {
    throw new Error(`${of} resolves through a cycle at ${target}`)
  }

  const next = byVariable.get(target)
  if (next === undefined) {
    throw new Error(`${of} points at ${target}, which nothing in :root declares`)
  }

  return resolve(of, next, byVariable, new Set([...seen, target]))
}

function refuseCollisions(tokens: Token[]): void {
  const seen = new Map<string, string>()

  for (const { name, cssVariable } of tokens) {
    const first = seen.get(name)
    if (first !== undefined) {
      throw new Error(`${first} and ${cssVariable} both fold to the key ${name}`)
    }

    seen.set(name, cssVariable)
  }
}

function stripComments(css: string): string {
  // Replaced by a space rather than removed: `--a:/* note */1rem` must not become `--a:1rem` by
  // accident in one place and `--a:  1rem` in another.
  return css.replace(/\/\*[\s\S]*?\*\//g, ' ')
}

function firstRoot(css: string): string {
  const opening = css.indexOf(':root')
  if (opening < 0) throw new Error('the stylesheet declares no :root')

  const brace = css.indexOf('{', opening)
  const closing = css.indexOf('}', brace)
  if (brace < 0 || closing < 0) throw new Error('the :root block is not closed')

  return css.slice(brace + 1, closing)
}

function camelCase(cssVariable: string): string {
  return cssVariable.replace(/^--/, '').replace(/-([a-z0-9])/g, (_, next: string) => next.toUpperCase())
}

function quote(value: string): string {
  return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`
}
