// Generated once by scripts/seed-overview-fixture.ts from the frozen prototype. Committed, and not
// regenerated by the gate: this is scaffolding the first live read replaces, and pinning it to the
// prototype for the rest of its life would pin the wrong thing.
//
// Every derived number is already here — what a patient has lost, how far along the goal they are, the
// stats strip, the roster tab counters, the biomarker verdicts. The prototype worked all of them out in
// its components; this is the same arithmetic, done once and on the far side of the seam.
import type { Overview, Patient } from '../overview'

export const PATIENTS: readonly Patient[] = [
  {
    "id": "marina",
    "name": "Марина Левченко",
    "age": 41,
    "initial": "М",
    "compound": "Семаглутид",
    "dose": "1,0 мг",
    "cadence": "еженедельно",
    "week": 12,
    "cycleLength": 12,
    "status": "attention",
    "adherence": 96,
    "lastSeen": "2 ч назад",
    "flags": [
      "cycle",
      "message"
    ],
    "note": "Цикл завершается в воскресенье — решение о продлении или паузе.",
    "weight": 110,
    "weightStart": 118,
    "goal": 100,
    "unit": "кг",
    "lostKg": 8,
    "goalProgressPct": 44,
    "spark": [
      0.92,
      0.8,
      0.7,
      0.6,
      0.55,
      0.52,
      0.5,
      0.49
    ],
    "biomarkers": [
      {
        "key": "hrv",
        "label": "HRV",
        "unit": "мс",
        "range": {
          "min": 58
        },
        "value": 71,
        "withinRange": true
      },
      {
        "key": "rhr",
        "label": "ЧСС покоя",
        "unit": "уд/мин",
        "range": {
          "max": 60
        },
        "value": 58,
        "withinRange": true
      },
      {
        "key": "sleep",
        "label": "Сон",
        "unit": "/100",
        "range": {
          "min": 75
        },
        "value": 87,
        "withinRange": true
      }
    ]
  },
  {
    "id": "oleg",
    "name": "Олег Самойлов",
    "age": 47,
    "initial": "О",
    "compound": "Тирзепатид",
    "dose": "5,0 мг",
    "cadence": "еженедельно",
    "week": 5,
    "cycleLength": 12,
    "status": "attention",
    "adherence": 71,
    "lastSeen": "вчера",
    "flags": [
      "missed",
      "biomarker"
    ],
    "note": "Две пропущенные дозы подряд, вес пошёл вверх. Нужен звонок.",
    "weight": 104.2,
    "weightStart": 109,
    "goal": 92,
    "unit": "кг",
    "lostKg": 4.8,
    "goalProgressPct": 28,
    "spark": [
      0.42,
      0.46,
      0.44,
      0.52,
      0.55,
      0.62,
      0.66,
      0.7
    ],
    "biomarkers": [
      {
        "key": "hrv",
        "label": "HRV",
        "unit": "мс",
        "range": {
          "min": 58
        },
        "value": 48,
        "withinRange": false
      },
      {
        "key": "rhr",
        "label": "ЧСС покоя",
        "unit": "уд/мин",
        "range": {
          "max": 60
        },
        "value": 67,
        "withinRange": false
      },
      {
        "key": "sleep",
        "label": "Сон",
        "unit": "/100",
        "range": {
          "min": 75
        },
        "value": 64,
        "withinRange": false
      }
    ]
  },
  {
    "id": "sofia",
    "name": "София Ермакова",
    "age": 35,
    "initial": "С",
    "compound": "Семаглутид",
    "dose": "0,5 мг",
    "cadence": "еженедельно",
    "week": 7,
    "cycleLength": 12,
    "status": "attention",
    "adherence": 88,
    "lastSeen": "5 ч назад",
    "flags": [
      "side",
      "message"
    ],
    "note": "Тошнота на третий день после дозы — третий эпизод за неделю.",
    "weight": 71.8,
    "weightStart": 78,
    "goal": 66,
    "unit": "кг",
    "lostKg": 6.2,
    "goalProgressPct": 52,
    "spark": [
      0.7,
      0.62,
      0.68,
      0.55,
      0.6,
      0.5,
      0.54,
      0.46
    ],
    "biomarkers": [
      {
        "key": "hrv",
        "label": "HRV",
        "unit": "мс",
        "range": {
          "min": 58
        },
        "value": 59,
        "withinRange": true
      },
      {
        "key": "rhr",
        "label": "ЧСС покоя",
        "unit": "уд/мин",
        "range": {
          "max": 60
        },
        "value": 62,
        "withinRange": false
      },
      {
        "key": "sleep",
        "label": "Сон",
        "unit": "/100",
        "range": {
          "min": 75
        },
        "value": 70,
        "withinRange": false
      }
    ]
  },
  {
    "id": "dmitri",
    "name": "Дмитрий Орлов",
    "age": 52,
    "initial": "Д",
    "compound": "Тесаморелин",
    "dose": "2,0 мг",
    "cadence": "ежедневно",
    "week": 9,
    "cycleLength": 12,
    "status": "attention",
    "adherence": 82,
    "lastSeen": "3 дн назад",
    "flags": [
      "biomarker",
      "titration"
    ],
    "note": "HRV просел две недели подряд, прогресс по весу встал.",
    "weight": 88.4,
    "weightStart": 94,
    "goal": 84,
    "unit": "кг",
    "lostKg": 5.6,
    "goalProgressPct": 56,
    "spark": [
      0.8,
      0.7,
      0.62,
      0.58,
      0.57,
      0.58,
      0.57,
      0.58
    ],
    "biomarkers": [
      {
        "key": "hrv",
        "label": "HRV",
        "unit": "мс",
        "range": {
          "min": 58
        },
        "value": 41,
        "withinRange": false
      },
      {
        "key": "rhr",
        "label": "ЧСС покоя",
        "unit": "уд/мин",
        "range": {
          "max": 60
        },
        "value": 64,
        "withinRange": false
      },
      {
        "key": "sleep",
        "label": "Сон",
        "unit": "/100",
        "range": {
          "min": 75
        },
        "value": 61,
        "withinRange": false
      }
    ]
  },
  {
    "id": "anna",
    "name": "Анна Кравцова",
    "age": 38,
    "initial": "А",
    "compound": "Семаглутид",
    "dose": "0,25 мг",
    "cadence": "еженедельно",
    "week": 2,
    "cycleLength": 12,
    "status": "watch",
    "adherence": 100,
    "lastSeen": "1 ч назад",
    "flags": [
      "message"
    ],
    "note": "Первая титрация через неделю — вопрос про утренний приём.",
    "weight": 82.1,
    "weightStart": 84,
    "goal": 72,
    "unit": "кг",
    "lostKg": 1.9,
    "goalProgressPct": 16,
    "spark": [
      0.98,
      0.96,
      0.93,
      0.9,
      0.88,
      0.85,
      0.83,
      0.8
    ],
    "biomarkers": [
      {
        "key": "hrv",
        "label": "HRV",
        "unit": "мс",
        "range": {
          "min": 58
        },
        "value": 63,
        "withinRange": true
      },
      {
        "key": "rhr",
        "label": "ЧСС покоя",
        "unit": "уд/мин",
        "range": {
          "max": 60
        },
        "value": 60,
        "withinRange": true
      },
      {
        "key": "sleep",
        "label": "Сон",
        "unit": "/100",
        "range": {
          "min": 75
        },
        "value": 74,
        "withinRange": false
      }
    ]
  },
  {
    "id": "pavel",
    "name": "Павел Гордеев",
    "age": 44,
    "initial": "П",
    "compound": "BPC-157",
    "dose": "250 мкг",
    "cadence": "ежедневно",
    "week": 4,
    "cycleLength": 8,
    "status": "watch",
    "adherence": 79,
    "lastSeen": "вчера",
    "flags": [
      "missed"
    ],
    "note": "Восстановление связки — одна пропущенная инъекция в среду.",
    "weight": 91,
    "weightStart": 92.5,
    "goal": 88,
    "unit": "кг",
    "lostKg": 1.5,
    "goalProgressPct": 33,
    "spark": [
      0.8,
      0.7,
      0.62,
      0.58,
      0.57,
      0.58,
      0.57,
      0.58
    ],
    "biomarkers": [
      {
        "key": "hrv",
        "label": "HRV",
        "unit": "мс",
        "range": {
          "min": 58
        },
        "value": 55,
        "withinRange": false
      },
      {
        "key": "rhr",
        "label": "ЧСС покоя",
        "unit": "уд/мин",
        "range": {
          "max": 60
        },
        "value": 59,
        "withinRange": true
      },
      {
        "key": "sleep",
        "label": "Сон",
        "unit": "/100",
        "range": {
          "min": 75
        },
        "value": 68,
        "withinRange": false
      }
    ]
  },
  {
    "id": "irina",
    "name": "Ирина Соколова",
    "age": 49,
    "initial": "И",
    "compound": "Тирзепатид",
    "dose": "2,5 мг",
    "cadence": "еженедельно",
    "week": 3,
    "cycleLength": 12,
    "status": "watch",
    "adherence": 92,
    "lastSeen": "6 ч назад",
    "flags": [
      "titration"
    ],
    "note": "Хорошо переносит — на следующей неделе подъём до 5,0 мг.",
    "weight": 96.3,
    "weightStart": 99,
    "goal": 84,
    "unit": "кг",
    "lostKg": 2.7,
    "goalProgressPct": 18,
    "spark": [
      0.95,
      0.88,
      0.82,
      0.74,
      0.66,
      0.58,
      0.5,
      0.42
    ],
    "biomarkers": [
      {
        "key": "hrv",
        "label": "HRV",
        "unit": "мс",
        "range": {
          "min": 58
        },
        "value": 58,
        "withinRange": true
      },
      {
        "key": "rhr",
        "label": "ЧСС покоя",
        "unit": "уд/мин",
        "range": {
          "max": 60
        },
        "value": 61,
        "withinRange": false
      },
      {
        "key": "sleep",
        "label": "Сон",
        "unit": "/100",
        "range": {
          "min": 75
        },
        "value": 72,
        "withinRange": false
      }
    ]
  },
  {
    "id": "viktor",
    "name": "Виктор Зайцев",
    "age": 56,
    "initial": "В",
    "compound": "CJC-1295",
    "dose": "100 мкг",
    "cadence": "2× в неделю",
    "week": 6,
    "cycleLength": 10,
    "status": "watch",
    "adherence": 85,
    "lastSeen": "2 дн назад",
    "flags": [
      "message"
    ],
    "note": "Спрашивает про сочетание с тренировками натощак.",
    "weight": 99.5,
    "weightStart": 102,
    "goal": 90,
    "unit": "кг",
    "lostKg": 2.5,
    "goalProgressPct": 21,
    "spark": [
      0.7,
      0.62,
      0.68,
      0.55,
      0.6,
      0.5,
      0.54,
      0.46
    ],
    "biomarkers": [
      {
        "key": "hrv",
        "label": "HRV",
        "unit": "мс",
        "range": {
          "min": 58
        },
        "value": 52,
        "withinRange": false
      },
      {
        "key": "rhr",
        "label": "ЧСС покоя",
        "unit": "уд/мин",
        "range": {
          "max": 60
        },
        "value": 63,
        "withinRange": false
      },
      {
        "key": "sleep",
        "label": "Сон",
        "unit": "/100",
        "range": {
          "min": 75
        },
        "value": 66,
        "withinRange": false
      }
    ]
  },
  {
    "id": "elena",
    "name": "Елена Власова",
    "age": 36,
    "initial": "Е",
    "compound": "Семаглутид",
    "dose": "1,0 мг",
    "cadence": "еженедельно",
    "week": 10,
    "cycleLength": 12,
    "status": "track",
    "adherence": 98,
    "lastSeen": "4 ч назад",
    "flags": [],
    "note": "",
    "weight": 68.2,
    "weightStart": 79,
    "goal": 65,
    "unit": "кг",
    "lostKg": 10.8,
    "goalProgressPct": 77,
    "spark": [
      0.95,
      0.88,
      0.82,
      0.74,
      0.66,
      0.58,
      0.5,
      0.42
    ],
    "biomarkers": [
      {
        "key": "hrv",
        "label": "HRV",
        "unit": "мс",
        "range": {
          "min": 58
        },
        "value": 69,
        "withinRange": true
      },
      {
        "key": "rhr",
        "label": "ЧСС покоя",
        "unit": "уд/мин",
        "range": {
          "max": 60
        },
        "value": 56,
        "withinRange": true
      },
      {
        "key": "sleep",
        "label": "Сон",
        "unit": "/100",
        "range": {
          "min": 75
        },
        "value": 88,
        "withinRange": true
      }
    ]
  },
  {
    "id": "roman",
    "name": "Роман Беляев",
    "age": 43,
    "initial": "Р",
    "compound": "Тирзепатид",
    "dose": "7,5 мг",
    "cadence": "еженедельно",
    "week": 8,
    "cycleLength": 12,
    "status": "track",
    "adherence": 100,
    "lastSeen": "сегодня",
    "flags": [],
    "note": "",
    "weight": 95,
    "weightStart": 108,
    "goal": 88,
    "unit": "кг",
    "lostKg": 13,
    "goalProgressPct": 65,
    "spark": [
      0.95,
      0.88,
      0.82,
      0.74,
      0.66,
      0.58,
      0.5,
      0.42
    ],
    "biomarkers": [
      {
        "key": "hrv",
        "label": "HRV",
        "unit": "мс",
        "range": {
          "min": 58
        },
        "value": 66,
        "withinRange": true
      },
      {
        "key": "rhr",
        "label": "ЧСС покоя",
        "unit": "уд/мин",
        "range": {
          "max": 60
        },
        "value": 57,
        "withinRange": true
      },
      {
        "key": "sleep",
        "label": "Сон",
        "unit": "/100",
        "range": {
          "min": 75
        },
        "value": 84,
        "withinRange": true
      }
    ]
  },
  {
    "id": "natalia",
    "name": "Наталья Демина",
    "age": 39,
    "initial": "Н",
    "compound": "Семаглутид",
    "dose": "0,5 мг",
    "cadence": "еженедельно",
    "week": 6,
    "cycleLength": 12,
    "status": "track",
    "adherence": 94,
    "lastSeen": "8 ч назад",
    "flags": [],
    "note": "",
    "weight": 74.4,
    "weightStart": 81,
    "goal": 68,
    "unit": "кг",
    "lostKg": 6.6,
    "goalProgressPct": 51,
    "spark": [
      0.92,
      0.8,
      0.7,
      0.6,
      0.55,
      0.52,
      0.5,
      0.49
    ],
    "biomarkers": [
      {
        "key": "hrv",
        "label": "HRV",
        "unit": "мс",
        "range": {
          "min": 58
        },
        "value": 64,
        "withinRange": true
      },
      {
        "key": "rhr",
        "label": "ЧСС покоя",
        "unit": "уд/мин",
        "range": {
          "max": 60
        },
        "value": 59,
        "withinRange": true
      },
      {
        "key": "sleep",
        "label": "Сон",
        "unit": "/100",
        "range": {
          "min": 75
        },
        "value": 80,
        "withinRange": true
      }
    ]
  },
  {
    "id": "andrei",
    "name": "Андрей Тихонов",
    "age": 50,
    "initial": "А",
    "compound": "Ипаморелин",
    "dose": "200 мкг",
    "cadence": "ежедневно",
    "week": 5,
    "cycleLength": 10,
    "status": "track",
    "adherence": 91,
    "lastSeen": "вчера",
    "flags": [],
    "note": "",
    "weight": 86.7,
    "weightStart": 90,
    "goal": 82,
    "unit": "кг",
    "lostKg": 3.3,
    "goalProgressPct": 41,
    "spark": [
      0.7,
      0.62,
      0.68,
      0.55,
      0.6,
      0.5,
      0.54,
      0.46
    ],
    "biomarkers": [
      {
        "key": "hrv",
        "label": "HRV",
        "unit": "мс",
        "range": {
          "min": 58
        },
        "value": 61,
        "withinRange": true
      },
      {
        "key": "rhr",
        "label": "ЧСС покоя",
        "unit": "уд/мин",
        "range": {
          "max": 60
        },
        "value": 58,
        "withinRange": true
      },
      {
        "key": "sleep",
        "label": "Сон",
        "unit": "/100",
        "range": {
          "min": 75
        },
        "value": 78,
        "withinRange": true
      }
    ]
  },
  {
    "id": "yulia",
    "name": "Юлия Фомина",
    "age": 33,
    "initial": "Ю",
    "compound": "Семаглутид",
    "dose": "0,25 мг",
    "cadence": "еженедельно",
    "week": 3,
    "cycleLength": 12,
    "status": "track",
    "adherence": 100,
    "lastSeen": "3 ч назад",
    "flags": [],
    "note": "",
    "weight": 77,
    "weightStart": 80,
    "goal": 70,
    "unit": "кг",
    "lostKg": 3,
    "goalProgressPct": 30,
    "spark": [
      0.98,
      0.96,
      0.93,
      0.9,
      0.88,
      0.85,
      0.83,
      0.8
    ],
    "biomarkers": [
      {
        "key": "hrv",
        "label": "HRV",
        "unit": "мс",
        "range": {
          "min": 58
        },
        "value": 62,
        "withinRange": true
      },
      {
        "key": "rhr",
        "label": "ЧСС покоя",
        "unit": "уд/мин",
        "range": {
          "max": 60
        },
        "value": 60,
        "withinRange": true
      },
      {
        "key": "sleep",
        "label": "Сон",
        "unit": "/100",
        "range": {
          "min": 75
        },
        "value": 76,
        "withinRange": true
      }
    ]
  },
  {
    "id": "maxim",
    "name": "Максим Корнев",
    "age": 46,
    "initial": "М",
    "compound": "TB-500",
    "dose": "2,0 мг",
    "cadence": "2× в неделю",
    "week": 7,
    "cycleLength": 8,
    "status": "track",
    "adherence": 96,
    "lastSeen": "сегодня",
    "flags": [],
    "note": "",
    "weight": 93.2,
    "weightStart": 96,
    "goal": 90,
    "unit": "кг",
    "lostKg": 2.8,
    "goalProgressPct": 47,
    "spark": [
      0.95,
      0.88,
      0.82,
      0.74,
      0.66,
      0.58,
      0.5,
      0.42
    ],
    "biomarkers": [
      {
        "key": "hrv",
        "label": "HRV",
        "unit": "мс",
        "range": {
          "min": 58
        },
        "value": 60,
        "withinRange": true
      },
      {
        "key": "rhr",
        "label": "ЧСС покоя",
        "unit": "уд/мин",
        "range": {
          "max": 60
        },
        "value": 58,
        "withinRange": true
      },
      {
        "key": "sleep",
        "label": "Сон",
        "unit": "/100",
        "range": {
          "min": 75
        },
        "value": 79,
        "withinRange": true
      }
    ]
  },
  {
    "id": "galina",
    "name": "Галина Орехова",
    "age": 54,
    "initial": "Г",
    "compound": "Тирзепатид",
    "dose": "5,0 мг",
    "cadence": "еженедельно",
    "week": 11,
    "cycleLength": 12,
    "status": "track",
    "adherence": 99,
    "lastSeen": "5 ч назад",
    "flags": [],
    "note": "",
    "weight": 81.5,
    "weightStart": 95,
    "goal": 78,
    "unit": "кг",
    "lostKg": 13.5,
    "goalProgressPct": 79,
    "spark": [
      0.95,
      0.88,
      0.82,
      0.74,
      0.66,
      0.58,
      0.5,
      0.42
    ],
    "biomarkers": [
      {
        "key": "hrv",
        "label": "HRV",
        "unit": "мс",
        "range": {
          "min": 58
        },
        "value": 67,
        "withinRange": true
      },
      {
        "key": "rhr",
        "label": "ЧСС покоя",
        "unit": "уд/мин",
        "range": {
          "max": 60
        },
        "value": 56,
        "withinRange": true
      },
      {
        "key": "sleep",
        "label": "Сон",
        "unit": "/100",
        "range": {
          "min": 75
        },
        "value": 85,
        "withinRange": true
      }
    ]
  },
  {
    "id": "sergei",
    "name": "Сергей Лапин",
    "age": 41,
    "initial": "С",
    "compound": "Семаглутид",
    "dose": "1,0 мг",
    "cadence": "еженедельно",
    "week": 9,
    "cycleLength": 12,
    "status": "track",
    "adherence": 93,
    "lastSeen": "вчера",
    "flags": [],
    "note": "",
    "weight": 89,
    "weightStart": 101,
    "goal": 84,
    "unit": "кг",
    "lostKg": 12,
    "goalProgressPct": 71,
    "spark": [
      0.92,
      0.8,
      0.7,
      0.6,
      0.55,
      0.52,
      0.5,
      0.49
    ],
    "biomarkers": [
      {
        "key": "hrv",
        "label": "HRV",
        "unit": "мс",
        "range": {
          "min": 58
        },
        "value": 63,
        "withinRange": true
      },
      {
        "key": "rhr",
        "label": "ЧСС покоя",
        "unit": "уд/мин",
        "range": {
          "max": 60
        },
        "value": 57,
        "withinRange": true
      },
      {
        "key": "sleep",
        "label": "Сон",
        "unit": "/100",
        "range": {
          "min": 75
        },
        "value": 81,
        "withinRange": true
      }
    ]
  },
  {
    "id": "kira",
    "name": "Кира Жукова",
    "age": 37,
    "initial": "К",
    "compound": "Ретатрутид",
    "dose": "4,0 мг",
    "cadence": "еженедельно",
    "week": 4,
    "cycleLength": 12,
    "status": "track",
    "adherence": 97,
    "lastSeen": "7 ч назад",
    "flags": [],
    "note": "",
    "weight": 84.3,
    "weightStart": 90,
    "goal": 76,
    "unit": "кг",
    "lostKg": 5.7,
    "goalProgressPct": 41,
    "spark": [
      0.95,
      0.88,
      0.82,
      0.74,
      0.66,
      0.58,
      0.5,
      0.42
    ],
    "biomarkers": [
      {
        "key": "hrv",
        "label": "HRV",
        "unit": "мс",
        "range": {
          "min": 58
        },
        "value": 65,
        "withinRange": true
      },
      {
        "key": "rhr",
        "label": "ЧСС покоя",
        "unit": "уд/мин",
        "range": {
          "max": 60
        },
        "value": 58,
        "withinRange": true
      },
      {
        "key": "sleep",
        "label": "Сон",
        "unit": "/100",
        "range": {
          "min": 75
        },
        "value": 82,
        "withinRange": true
      }
    ]
  },
  {
    "id": "boris",
    "name": "Борис Шевцов",
    "age": 58,
    "initial": "Б",
    "compound": "Тесаморелин",
    "dose": "1,0 мг",
    "cadence": "ежедневно",
    "week": 8,
    "cycleLength": 12,
    "status": "track",
    "adherence": 90,
    "lastSeen": "2 дн назад",
    "flags": [],
    "note": "",
    "weight": 97.8,
    "weightStart": 104,
    "goal": 92,
    "unit": "кг",
    "lostKg": 6.2,
    "goalProgressPct": 52,
    "spark": [
      0.7,
      0.62,
      0.68,
      0.55,
      0.6,
      0.5,
      0.54,
      0.46
    ],
    "biomarkers": [
      {
        "key": "hrv",
        "label": "HRV",
        "unit": "мс",
        "range": {
          "min": 58
        },
        "value": 54,
        "withinRange": false
      },
      {
        "key": "rhr",
        "label": "ЧСС покоя",
        "unit": "уд/мин",
        "range": {
          "max": 60
        },
        "value": 60,
        "withinRange": true
      },
      {
        "key": "sleep",
        "label": "Сон",
        "unit": "/100",
        "range": {
          "min": 75
        },
        "value": 73,
        "withinRange": false
      }
    ]
  },
  {
    "id": "vera",
    "name": "Вера Зорина",
    "age": 45,
    "initial": "В",
    "compound": "Семаглутид",
    "dose": "0,5 мг",
    "cadence": "еженедельно",
    "week": 5,
    "cycleLength": 12,
    "status": "track",
    "adherence": 95,
    "lastSeen": "4 ч назад",
    "flags": [],
    "note": "",
    "weight": 79.1,
    "weightStart": 86,
    "goal": 72,
    "unit": "кг",
    "lostKg": 6.9,
    "goalProgressPct": 49,
    "spark": [
      0.92,
      0.8,
      0.7,
      0.6,
      0.55,
      0.52,
      0.5,
      0.49
    ],
    "biomarkers": [
      {
        "key": "hrv",
        "label": "HRV",
        "unit": "мс",
        "range": {
          "min": 58
        },
        "value": 61,
        "withinRange": true
      },
      {
        "key": "rhr",
        "label": "ЧСС покоя",
        "unit": "уд/мин",
        "range": {
          "max": 60
        },
        "value": 59,
        "withinRange": true
      },
      {
        "key": "sleep",
        "label": "Сон",
        "unit": "/100",
        "range": {
          "min": 75
        },
        "value": 78,
        "withinRange": true
      }
    ]
  },
  {
    "id": "timur",
    "name": "Тимур Аскеров",
    "age": 42,
    "initial": "Т",
    "compound": "Тирзепатид",
    "dose": "10,0 мг",
    "cadence": "еженедельно",
    "week": 10,
    "cycleLength": 12,
    "status": "track",
    "adherence": 98,
    "lastSeen": "сегодня",
    "flags": [],
    "note": "",
    "weight": 102.4,
    "weightStart": 118,
    "goal": 95,
    "unit": "кг",
    "lostKg": 15.6,
    "goalProgressPct": 68,
    "spark": [
      0.95,
      0.88,
      0.82,
      0.74,
      0.66,
      0.58,
      0.5,
      0.42
    ],
    "biomarkers": [
      {
        "key": "hrv",
        "label": "HRV",
        "unit": "мс",
        "range": {
          "min": 58
        },
        "value": 64,
        "withinRange": true
      },
      {
        "key": "rhr",
        "label": "ЧСС покоя",
        "unit": "уд/мин",
        "range": {
          "max": 60
        },
        "value": 57,
        "withinRange": true
      },
      {
        "key": "sleep",
        "label": "Сон",
        "unit": "/100",
        "range": {
          "min": 75
        },
        "value": 83,
        "withinRange": true
      }
    ]
  },
  {
    "id": "lidia",
    "name": "Лидия Панова",
    "age": 51,
    "initial": "Л",
    "compound": "CJC-1295",
    "dose": "100 мкг",
    "cadence": "2× в неделю",
    "week": 6,
    "cycleLength": 10,
    "status": "track",
    "adherence": 92,
    "lastSeen": "вчера",
    "flags": [],
    "note": "",
    "weight": 75.6,
    "weightStart": 80,
    "goal": 70,
    "unit": "кг",
    "lostKg": 4.4,
    "goalProgressPct": 44,
    "spark": [
      0.7,
      0.62,
      0.68,
      0.55,
      0.6,
      0.5,
      0.54,
      0.46
    ],
    "biomarkers": [
      {
        "key": "hrv",
        "label": "HRV",
        "unit": "мс",
        "range": {
          "min": 58
        },
        "value": 59,
        "withinRange": true
      },
      {
        "key": "rhr",
        "label": "ЧСС покоя",
        "unit": "уд/мин",
        "range": {
          "max": 60
        },
        "value": 58,
        "withinRange": true
      },
      {
        "key": "sleep",
        "label": "Сон",
        "unit": "/100",
        "range": {
          "min": 75
        },
        "value": 77,
        "withinRange": true
      }
    ]
  },
  {
    "id": "egor",
    "name": "Егор Власенко",
    "age": 39,
    "initial": "Е",
    "compound": "Семаглутид",
    "dose": "0,25 мг",
    "cadence": "еженедельно",
    "week": 1,
    "cycleLength": 12,
    "status": "track",
    "adherence": 100,
    "lastSeen": "6 ч назад",
    "flags": [],
    "note": "",
    "weight": 88,
    "weightStart": 89,
    "goal": 80,
    "unit": "кг",
    "lostKg": 1,
    "goalProgressPct": 11,
    "spark": [
      0.98,
      0.96,
      0.93,
      0.9,
      0.88,
      0.85,
      0.83,
      0.8
    ],
    "biomarkers": [
      {
        "key": "hrv",
        "label": "HRV",
        "unit": "мс",
        "range": {
          "min": 58
        },
        "value": 60,
        "withinRange": true
      },
      {
        "key": "rhr",
        "label": "ЧСС покоя",
        "unit": "уд/мин",
        "range": {
          "max": 60
        },
        "value": 61,
        "withinRange": false
      },
      {
        "key": "sleep",
        "label": "Сон",
        "unit": "/100",
        "range": {
          "min": 75
        },
        "value": 75,
        "withinRange": true
      }
    ]
  },
  {
    "id": "alina",
    "name": "Алина Серова",
    "age": 34,
    "initial": "А",
    "compound": "Ипаморелин",
    "dose": "200 мкг",
    "cadence": "ежедневно",
    "week": 7,
    "cycleLength": 10,
    "status": "track",
    "adherence": 96,
    "lastSeen": "3 ч назад",
    "flags": [],
    "note": "",
    "weight": 64.8,
    "weightStart": 69,
    "goal": 60,
    "unit": "кг",
    "lostKg": 4.2,
    "goalProgressPct": 47,
    "spark": [
      0.92,
      0.8,
      0.7,
      0.6,
      0.55,
      0.52,
      0.5,
      0.49
    ],
    "biomarkers": [
      {
        "key": "hrv",
        "label": "HRV",
        "unit": "мс",
        "range": {
          "min": 58
        },
        "value": 66,
        "withinRange": true
      },
      {
        "key": "rhr",
        "label": "ЧСС покоя",
        "unit": "уд/мин",
        "range": {
          "max": 60
        },
        "value": 57,
        "withinRange": true
      },
      {
        "key": "sleep",
        "label": "Сон",
        "unit": "/100",
        "range": {
          "min": 75
        },
        "value": 84,
        "withinRange": true
      }
    ]
  },
  {
    "id": "nikita",
    "name": "Никита Громов",
    "age": 48,
    "initial": "Н",
    "compound": "Тирзепатид",
    "dose": "5,0 мг",
    "cadence": "еженедельно",
    "week": 9,
    "cycleLength": 12,
    "status": "track",
    "adherence": 94,
    "lastSeen": "вчера",
    "flags": [],
    "note": "",
    "weight": 100.1,
    "weightStart": 112,
    "goal": 92,
    "unit": "кг",
    "lostKg": 11.9,
    "goalProgressPct": 60,
    "spark": [
      0.95,
      0.88,
      0.82,
      0.74,
      0.66,
      0.58,
      0.5,
      0.42
    ],
    "biomarkers": [
      {
        "key": "hrv",
        "label": "HRV",
        "unit": "мс",
        "range": {
          "min": 58
        },
        "value": 62,
        "withinRange": true
      },
      {
        "key": "rhr",
        "label": "ЧСС покоя",
        "unit": "уд/мин",
        "range": {
          "max": 60
        },
        "value": 58,
        "withinRange": true
      },
      {
        "key": "sleep",
        "label": "Сон",
        "unit": "/100",
        "range": {
          "min": 75
        },
        "value": 80,
        "withinRange": true
      }
    ]
  },
  {
    "id": "darya",
    "name": "Дарья Котова",
    "age": 40,
    "initial": "Д",
    "compound": "Семаглутид",
    "dose": "0,5 мг",
    "cadence": "еженедельно",
    "week": 4,
    "cycleLength": 12,
    "status": "track",
    "adherence": 97,
    "lastSeen": "5 ч назад",
    "flags": [],
    "note": "",
    "weight": 73.7,
    "weightStart": 79,
    "goal": 68,
    "unit": "кг",
    "lostKg": 5.3,
    "goalProgressPct": 48,
    "spark": [
      0.92,
      0.8,
      0.7,
      0.6,
      0.55,
      0.52,
      0.5,
      0.49
    ],
    "biomarkers": [
      {
        "key": "hrv",
        "label": "HRV",
        "unit": "мс",
        "range": {
          "min": 58
        },
        "value": 63,
        "withinRange": true
      },
      {
        "key": "rhr",
        "label": "ЧСС покоя",
        "unit": "уд/мин",
        "range": {
          "max": 60
        },
        "value": 59,
        "withinRange": true
      },
      {
        "key": "sleep",
        "label": "Сон",
        "unit": "/100",
        "range": {
          "min": 75
        },
        "value": 79,
        "withinRange": true
      }
    ]
  }
]

export const TRIAGE_IDS: readonly string[] = ["marina","oleg","sofia","dmitri"]

export const OVERVIEW: Omit<Overview, 'triage'> = {
  "doctor": {
    "name": "Ксения Первеева",
    "initial": "К"
  },
  "aggregates": {
    "patients": 25,
    "attention": 4,
    "watch": 4,
    "dosesToday": 6,
    "dosesDone": 3,
    "unread": 4,
    "averageAdherence": 93,
    "byStatus": {
      "all": 25,
      "attention": 4,
      "watch": 4,
      "track": 17
    }
  },
  "schedule": [
    {
      "id": "s1",
      "patientId": "marina",
      "at": "07:00",
      "kind": "dose",
      "label": "Семаглутид · 1,0 мг",
      "state": "done"
    },
    {
      "id": "s2",
      "patientId": "dmitri",
      "at": "07:30",
      "kind": "dose",
      "label": "Тесаморелин · 2,0 мг",
      "state": "done"
    },
    {
      "id": "s3",
      "patientId": "roman",
      "at": "08:00",
      "kind": "dose",
      "label": "Тирзепатид · 7,5 мг",
      "state": "done"
    },
    {
      "id": "s4",
      "patientId": "sofia",
      "at": "09:15",
      "kind": "checkin",
      "label": "Звонок · побочные эффекты",
      "state": "now"
    },
    {
      "id": "s5",
      "patientId": "anna",
      "at": "11:00",
      "kind": "dose",
      "label": "Семаглутид · 0,25 мг",
      "state": "due"
    },
    {
      "id": "s6",
      "patientId": "oleg",
      "at": "13:30",
      "kind": "checkin",
      "label": "Звонок · пропуски дозы",
      "state": "due"
    },
    {
      "id": "s7",
      "patientId": "pavel",
      "at": "17:00",
      "kind": "dose",
      "label": "BPC-157 · 250 мкг",
      "state": "due"
    },
    {
      "id": "s8",
      "patientId": "andrei",
      "at": "19:00",
      "kind": "dose",
      "label": "Ипаморелин · 200 мкг",
      "state": "due"
    }
  ]
}
