package app.cadence.shared.repository

import app.cadence.shared.domain.Ingredient
import app.cadence.shared.domain.MealType
import app.cadence.shared.domain.Recipe
import app.cadence.shared.domain.RecipeId
import app.cadence.shared.domain.RecipeIngredient
import app.cadence.shared.domain.RecipeTag

/**
 * `RecipesScreen`'s two filters, independent and additive. `null` on either field is «Все»/
 * «Любые» — the screen's own "no filter" state, the same choice [RecipeDraft.prepMin] makes
 * for "not asked".
 */
data class RecipeFilter(
    val mealType: MealType? = null,
    val tag: RecipeTag? = null,
)

/**
 * Own recipes ahead of the clinic's, matching `AppState.tsx`'s `[...userRecipes,
 * ...RECIPES.STARTERS]` — told apart by [Recipe.ownerId], not by list half.
 */
data class RecipeList(
    val recipes: List<Recipe>,
)

/**
 * [mealType] defaults to [MealType.LUNCH] and [servings] to 2, matching the builder's own
 * pre-filled defaults — unlike `MealDraft`, a new recipe's type and serving count are never
 * "unset". [dek] is generated by the screen from the per-serving arithmetic, not required by
 * [RecipeDraft.canSave].
 */
data class RecipeDraft(
    val name: String? = null,
    val mealType: MealType = MealType.LUNCH,
    val tags: List<RecipeTag> = emptyList(),
    val servings: Int = 2,
    val prepMin: Int? = null,
    val cookMin: Int? = null,
    val dek: String? = null,
    val ingredients: List<RecipeIngredient> = emptyList(),
    val steps: List<String> = emptyList(),
) {
    /**
     * A non-blank name and at least one ingredient — `RecipeBuilderScreen`'s two
     * independently-checked save-blocking cases.
     */
    fun canSave(): Boolean = !name.isNullOrBlank() && ingredients.isNotEmpty()
}

/** What saving a recipe did. */
sealed interface RecipeSaveResult {
    data class Saved(
        val id: RecipeId,
    ) : RecipeSaveResult

    /** The draft cannot make a recipe — see [RecipeDraft.canSave]. */
    data object Rejected : RecipeSaveResult
}

/**
 * §11's recipe library and ingredient reference. A patient's own recipes live in a mutable
 * list on `CadenceMocks`, the same place meals do, not inside this repository's mock.
 */
interface RecipeRepository {
    /** The library, own recipes first, matching [filter]. */
    suspend fun library(filter: RecipeFilter): RecipeList

    /** One recipe by id, own or the clinic's, or null if it does not exist. */
    suspend fun recipe(id: RecipeId): Recipe?

    /** Ingredients whose name contains [query], case-insensitively and trimmed. */
    suspend fun ingredients(query: String): List<Ingredient>

    suspend fun save(draft: RecipeDraft): RecipeSaveResult
}
