package app.cadence.shared.repository

import app.cadence.shared.domain.Ingredient
import app.cadence.shared.domain.MealType
import app.cadence.shared.domain.Recipe
import app.cadence.shared.domain.RecipeId
import app.cadence.shared.domain.RecipeIngredient
import app.cadence.shared.domain.RecipeTag

/**
 * §09's two filters on the recipe list, independent and additive.
 *
 * `null` on either field is «Все» / «Любые» — the screen's own «no filter»
 * state — not a sentinel value standing in for it, the same choice
 * [RecipeDraft.prepMin] makes for «not asked».
 */
data class RecipeFilter(
    val mealType: MealType? = null,
    val tag: RecipeTag? = null,
)

/**
 * What `RecipeRepository.library` answers: own recipes ahead of the clinic's,
 * per `AppState.tsx:166`'s `[...userRecipes, ...RECIPES.STARTERS]` — a screen
 * tells the two apart by [Recipe.ownerId], not by which half of this list a
 * recipe sits in.
 */
data class RecipeList(
    val recipes: List<Recipe>,
)

/**
 * What becomes a [Recipe] when `RecipeRepository.save` writes it —
 * `RecipeBuilderScreen` (step-12) fills this in field by field.
 *
 * [mealType] defaults to [MealType.LUNCH] and [servings] to 2, matching the
 * builder's own pre-filled defaults (`RecipeBuilderScreen.tsx`'s «Обед» and
 * «Порций 2») — unlike `MealDraft`, where every field starts genuinely
 * unset, a new recipe's type and serving count are never in an «unset»
 * state for this draft to model. [dek] is generated by the screen from the
 * arithmetic step-8 adds (per-serving kcal and protein), not by this draft
 * or by [RecipeRepository.save] — [RecipeDraft.canSave] does not require it.
 */
data class RecipeDraft(
    val name: String? = null,
    val mealType: MealType = MealType.LUNCH,
    val tags: List<RecipeTag> = emptyList(),
    val servings: Int = 2,
    val prepMin: Int? = null,
    val cookMin: Int? = null,
    val dek: String? = null,
    val ingredients: List<RecipeIngredient> = emptyList(),
    val steps: List<String> = emptyList(),
) {
    /**
     * A non-blank name and at least one ingredient — `RecipeBuilderScreen`'s
     * two independently-checked save-blocking cases (step-12).
     */
    fun canSave(): Boolean = !name.isNullOrBlank() && ingredients.isNotEmpty()
}

/** What saving a recipe did. */
sealed interface RecipeSaveResult {
    data class Saved(
        val id: RecipeId,
    ) : RecipeSaveResult

    /** The draft cannot make a recipe — see [RecipeDraft.canSave]. */
    data object Rejected : RecipeSaveResult
}

/**
 * §11's recipe library and ingredient reference: the clinic's starter
 * recipes plus whatever the patient has saved themselves, and the 100 g
 * macro table a recipe's [Recipe.ingredients] point into.
 *
 * A patient's own recipes live in a mutable list on `CadenceMocks`, the same
 * place meals do, rather than inside this repository's mock — one source of
 * truth for what «own» means, kept next to `CadenceMocks`' other mutable
 * lists instead of scattering the pattern.
 */
interface RecipeRepository {
    /** The library, own recipes first, matching [filter]. */
    suspend fun library(filter: RecipeFilter): RecipeList

    /** One recipe by id, own or the clinic's, or null if it does not exist. */
    suspend fun recipe(id: RecipeId): Recipe?

    /** Ingredients whose name contains [query], case-insensitively. */
    suspend fun ingredients(query: String): List<Ingredient>

    suspend fun save(draft: RecipeDraft): RecipeSaveResult
}
